import {
  ArrowUpIcon,
  CreditCard,
  DollarSign,
  PieChart,
  TrendingUp,
  Home,
  Car,
  ShoppingBag,
  Coffee,
  Gamepad2,
  Zap,
  Heart,
} from "lucide-react";

// Stats Cards Data
export const statsCardsData = [
  {
    id: 1,
    title: "Total Balance",
    value: "$12,345.67",
    change: "+2.5%",
    changeType: "positive" as const,
    description: "from last month",
    icon: DollarSign,
    color: "blue",
  },
  {
    id: 2,
    title: "Monthly Income",
    value: "$5,200.00",
    change: "+8.2%",
    changeType: "positive" as const,
    description: "from last month",
    icon: TrendingUp,
    color: "green",
  },
  {
    id: 3,
    title: "Monthly Expenses",
    value: "$3,456.78",
    change: "-1.2%",
    changeType: "negative" as const,
    description: "from last month",
    icon: CreditCard,
    color: "red",
  },
  {
    id: 4,
    title: "Savings Goal",
    value: "68%",
    change: "$6,800 of $10,000 goal",
    changeType: "neutral" as const,
    description: "Emergency fund progress",
    icon: PieChart,
    color: "purple",
  },
];

// Recent Transactions Data
export const recentTransactionsData = [
  {
    id: 1,
    name: "Grocery Store",
    category: "Food",
    amount: -87.32,
    date: "Today, 2:30 PM",
    icon: ShoppingBag,
    color: "red",
  },
  {
    id: 2,
    name: "Salary Deposit",
    category: "Income",
    amount: 2600.0,
    date: "Yesterday, 9:00 AM",
    icon: ArrowUpIcon,
    color: "green",
  },
  {
    id: 3,
    name: "Rent Payment",
    category: "Housing",
    amount: -1200.0,
    date: "Dec 1, 2024",
    icon: Home,
    color: "blue",
  },
  {
    id: 4,
    name: "Gas Station",
    category: "Transportation",
    amount: -45.67,
    date: "Dec 2, 2024",
    icon: Car,
    color: "orange",
  },
  {
    id: 5,
    name: "Coffee Shop",
    category: "Food",
    amount: -12.5,
    date: "Dec 2, 2024",
    icon: Coffee,
    color: "brown",
  },
  {
    id: 6,
    name: "Freelance Payment",
    category: "Income",
    amount: 850.0,
    date: "Nov 30, 2024",
    icon: ArrowUpIcon,
    color: "green",
  },
];

// Budget Overview Data
export const budgetOverviewData = [
  {
    id: 1,
    category: "Food & Dining",
    spent: 456,
    budget: 600,
    color: "blue",
    icon: Coffee,
  },
  {
    id: 2,
    category: "Transportation",
    spent: 234,
    budget: 400,
    color: "green",
    icon: Car,
  },
  {
    id: 3,
    category: "Entertainment",
    spent: 189,
    budget: 300,
    color: "yellow",
    icon: Gamepad2,
  },
  {
    id: 4,
    category: "Shopping",
    spent: 345,
    budget: 250,
    color: "red",
    icon: ShoppingBag,
  },
  {
    id: 5,
    category: "Utilities",
    spent: 278,
    budget: 350,
    color: "purple",
    icon: Zap,
  },
  {
    id: 6,
    category: "Healthcare",
    spent: 125,
    budget: 200,
    color: "pink",
    icon: Heart,
  },
];

// Financial Goals Data
export const financialGoalsData = [
  {
    id: 1,
    name: "Emergency Fund",
    target: 10000,
    current: 6800,
    deadline: "Dec 2024",
    priority: "high" as const,
  },
  {
    id: 2,
    name: "Vacation Fund",
    target: 3000,
    current: 1200,
    deadline: "Jun 2025",
    priority: "medium" as const,
  },
  {
    id: 3,
    name: "New Car",
    target: 25000,
    current: 8500,
    deadline: "Dec 2025",
    priority: "low" as const,
  },
  {
    id: 4,
    name: "Home Down Payment",
    target: 50000,
    current: 15000,
    deadline: "Dec 2026",
    priority: "high" as const,
  },
];

// Investment Portfolio Data
export const investmentData = [
  {
    id: 1,
    name: "Stock Portfolio",
    value: 8500.0,
    change: 156.78,
    changePercent: 1.88,
    allocation: 45,
  },
  {
    id: 2,
    name: "Bonds",
    value: 3200.0,
    change: -23.45,
    changePercent: -0.73,
    allocation: 25,
  },
  {
    id: 3,
    name: "Crypto",
    value: 1800.0,
    change: 89.12,
    changePercent: 5.21,
    allocation: 15,
  },
  {
    id: 4,
    name: "Cash",
    value: 2500.0,
    change: 0,
    changePercent: 0,
    allocation: 15,
  },
];
