// import { type Transaction } from "../types/Transaction";

// export const dummyTransactions: Transaction[] = [
//   {
//     id: 1,
//     type: "income",
//     amount: 20000,
//     category: "Salary",
//     date: "2025-06-01",
//     description: "Monthly salary",
//   },
//   {
//     id: 2,
//     type: "expense",
//     amount: 2500,
//     category: "Groceries",
//     date: "2025-06-05",
//     description: "Weekly shopping",
//   },
//   {
//     id: 3,
//     type: "expense",
//     amount: 1200,
//     category: "Transport",
//     date: "2025-06-07",
//     description: "Fuel",
//   },
//   {
//     id: 4,
//     type: "income",
//     amount: 5000,
//     category: "Freelance",
//     date: "2025-06-10",
//     description: "Side project",
//   },
//   {
//     id: 5,
//     type: "income",
//     amount: 5000,
//     category: "Freelance",
//     date: "2025-06-10",
//     description: "Side project",
//   },
//   {
//     id: 6,
//     type: "income",
//     amount: 5000,
//     category: "Freelance",
//     date: "2025-06-10",
//     description: "Side project",
//   },
//   {
//     id: 7,
//     type: "income",
//     amount: 5000,
//     category: "Freelance",
//     date: "2025-06-10",
//     description: "Side project",
//   },
//   {
//     id: 8,
//     type: "income",
//     amount: 5000,
//     category: "Freelance",
//     date: "2025-06-10",
//     description: "Side project",
//   },
// ];
